// <auto-generated />
using System;
using HeroesDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroesDB.Migrations
{
    [DbContext(typeof(HeroesDBContext))]
    partial class HeroesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserRegistration.UserController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserRegistration.UserController+IHero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int?>("UserControllerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserControllerId");

                    b.ToTable("IHero");
                });

            modelBuilder.Entity("UserRegistration.UserController+IHero", b =>
                {
                    b.HasOne("UserRegistration.UserController", null)
                        .WithMany("CharacterList")
                        .HasForeignKey("UserControllerId");
                });

            modelBuilder.Entity("UserRegistration.UserController", b =>
                {
                    b.Navigation("CharacterList");
                });
#pragma warning restore 612, 618
        }
    }
}
